import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Box, Flex, Button, Text, Tag } from "@chakra-ui/react";
import { ArrowBackIcon, AddIcon, WarningIcon } from "@chakra-ui/icons";
import Link from "next/link";
import Data from "storedata.json";
import Image from "next/image";
import ReactHtmlParser, {
  processNodes,
  convertNodeToElement,
  htmlparser2,
} from "react-html-parser";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Navigation, Thumbs } from "swiper";

// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import Head from "next/head";

export default function ProductPage() {
  const router = useRouter();
  const { name } = router.query;
  const [product, setProduct] = useState();
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  const [colors, setColors] = useState(null);

  useEffect(() => {
    console.log(Data);
    const productFound = Data.find((product) => product.url === "/" + name);
    setProduct(productFound);
    if (productFound) {
      if (productFound.attributes !== null) {
        if (productFound.attributes.colors) {
          let colors = productFound.attributes.colors;
          setColors(colors);
        }
      }
    }
  }, [name]);

  if (!product) {
    return "Loading...";
  }

  return (
    <Box>
      <Link href="/" passHref>
        <Button leftIcon={<ArrowBackIcon />} variant="outline">
          Back
        </Button>{" "}
      </Link>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex mt={0} gap={20} justifyContent="center" wrap="wrap">
        <Box width={{ base: "100%", sm: "100%", md: "100%", lg: "40%" }}>
          <Swiper
            style={{
              "--swiper-navigation-color": "#fff",
              "--swiper-pagination-color": "#fff",
            }}
            navigation={true}
            spaceBetween={0}
            centeredSlides={true}
            thumbs={{
              swiper:
                thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null,
            }}
            modules={[FreeMode, Navigation, Thumbs]}
          >
            {product.otherImages.map((image, idx) => {
              return (
                <SwiperSlide key={idx}>
                  <Image src={image} height={300} width={600} alt={name} />
                </SwiperSlide>
              );
            })}
          </Swiper>

          <Swiper
            onSwiper={setThumbsSwiper}
            slidesPerView={4}
            spaceBetween={5}
            freeMode={true}
            watchSlidesProgress={true}
            modules={[FreeMode, Navigation, Thumbs]}
            className="mySwiper"
          >
            {product.otherImages.map((image, idx) => {
              return (
                <SwiperSlide key={idx}>
                  <Image src={image} height={500} width={500} alt={name} />
                </SwiperSlide>
              );
            })}
          </Swiper>
        </Box>
        <Box width={{ base: "100%", sm: "100%", md: "100%", lg: "40%" }}>
          <Text fontWeight="600" fontSize="2xl">
            {" "}
            {product.name}
          </Text>

          <Text color="green.800" fontWeight="500" fontSize="2xl">
            ₹{product.price}
          </Text>
          {product.priceType?.map((type, idx) => {
            return (
              <Tag key={idx} mr={3}>
                ₹{type.price} {type.text}
              </Tag>
            );
          })}
          {colors && (
            <Flex gap={2} mt={2}>
              {colors.map((color, idx) => {
                return (
                  <Button size="sm" key={idx}>
                    {color.name}
                  </Button>
                );
              })}
            </Flex>
          )}

          <Text mt={10}>{ReactHtmlParser(product.description)}</Text>
          <Button mt={10} variant="solid" colorScheme="green">
            ENQUIRE NOW
          </Button>
        </Box>
      </Flex>
    </Box>
  );
}
