import Head from "next/head";
import Arrivals from "@/components/Arrivals";

export default function Home() {
  return (
    <>
      <Head>
        <title>Athayog Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Arrivals />
    </>
  );
}
